name: simplebank
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://postgres:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
